* Tasks in-progress (Kanban board)

| Specify (_) | [[#specify-done-rule][Done]] | Implement (_) | [[#implement-done-rule][Done]] | Validate (_) | [[#validate-done-rule][Done]] |
|-------------+------+---------------+------+--------------+------|
|             |      |               |      |              |      |

* Backlog

| Task                 |
|----------------------|
|                      |

* Notes
** Pull criteria
   Work should only move from a major column to the corresponding "Done" column when it meets the requirements listed below.

*** Specify
    :PROPERTIES:
    :CUSTOM_ID: specify-done-rule
    :END:
    - undefined

*** Implement
    :PROPERTIES:
    :CUSTOM_ID: implement-done-rule
    :END:      
    - undefined
    
*** Validate
    :PROPERTIES:
    :CUSTOM_ID: validate-done-rulE
    :END:
    - undefined

** WIP limits
   Work-in-progress (WIP) limits are in parenthesis after each major category. WIP describes the total number of tasks in a category pair (named and "Done").

   As the "Specify" step frequently results in multiple specified tasks per input, the task count in this column is based on the number of input items currently represented (directly or by a derived task) in the category. If, for example, the "Specify" column contained one task, the specification of which resulted in 4 "Done" tasks, any or all of those four tasks count as a single collective task for the purposes of "Specify"'s WIP. Once those items are individually removed from "Done" into "Implement", their individual WIP contribution is 1.
