name: BayesianStellarEvolution-PackageName
category: application
author: Elliot Robinson
maintainer: elliot.robinson@rgoptech.com
copyright: '2019'
# license:
github: BayesianStellarEvolution/BayesianStellarEvolution

default-extensions:
  - OverloadedStrings
  - BangPatterns

ghc-options:
  - -Wall
  
library:
  source-dirs: src
  exposed-modules:
    Module
dependencies:
    - base >=4.10 && <5

executables:
  programName:
    main: Main.hs
    source-dirs: programName
    dependencies:
      - base
      - BayesianStellarEvolution-PackageName
    when:
    - condition: os(windows)
      buildable: true

tests:
  library-tests:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -rtsopts
    dependencies:
      - base
      - BayesianStellarEvolution-PackageName
      - hspec
      - QuickCheck
